// Auto-generated by scripts/generate-plugin-registry.mjs
import React from 'react'

export type WidgetLoader = () => Promise<{ default: React.ComponentType<any> }>
export const widgetRegistry: Record<string, WidgetLoader> = {
  'core/ActivityFeed': () => import('./core/ActivityFeed'),
  'notifier/NotificationSettings': () =>
    import('../../../../packages/plugins/notifier/src/ui/NotificationSettings'),
}
