// Auto-generated by scripts/generate-plugin-registry.mjs
export type PluginDescriptor = {
  id: string
  packageName: string
  permissions: string[]
  importRegister: () => Promise<{ register: (ctx: any) => void }>
}

export const plugins: PluginDescriptor[] = [
  {
    id: 'log-watcher',
    packageName: '@grofit/log-watcher-plugin',
    permissions: ['event.emit:feed.item'],
    importRegister: () => {
      const p = '../../../plugins/log-watcher/src/plugin' as string
      return import(p as any) as Promise<{ register: (ctx: any) => void }>
    },
  },
  {
    id: 'notifier',
    packageName: '@grofit/notifier-plugin',
    permissions: ['notifier.send'],
    importRegister: () => {
      const p = '../../../plugins/notifier/src/plugin' as string
      return import(p as any) as Promise<{ register: (ctx: any) => void }>
    },
  },
]
